const produtos = [
    {"produto": "CAPA PARA MAQUINA LORENA", "preco": "R$ 112,00"},
    {"produto": "CAPA DE COLCHÃO CASAL HELANCA", "preco": "R$ 85,00"},
    {"produto": "CAPA DE COLCHÃO SOLTEIRO HELANCA", "preco": "R$ 75,00"},
    {"produto": "CAPA DE COLCHÃO QUEEN HELANCA", "preco": "R$ 105,00"},
    {"produto": "CAPA DE COLCHÃO KING HELANCA", "preco": "R$ 79,00"},
    {"produto": "CAPA DE COLCHÃO CASAL RUBI", "preco": "R$ 95,00"},
    {"produto": "CAPA DE COLCHÃO SOLTEIRO RUBI", "preco": "R$ 80,00"},
    {"produto": "CAPA DE COLCHÃO QUEEN RUBI", "preco": "R$ 115,00"},
    {"produto": "PROTETOR DE COLCHÃO IMPERMEÁVEL CASA", "preco": "R$ 157,00"},
    {"produto": "PROTETOR DE COLCHÃO IMPERMEÁVEL SOLTEIRO", "preco": "R$ 125,00"},
    {"produto": "PROTETOR DE COLCHÃO IMPERMEÁVEL QUEEN", "preco": "R$ 174,00"},
    {"produto": "CAPA DE SOFÁ 2 E 3 LUGARES LISA", "preco": "R$ 251,00"},
    {"produto": "CAPA DE SOFÁ 2 E 3 LUGARES EST.", "preco": "R$ 284,00"},
    {"produto": "LENÇOL CASAL MALHA", "preco": "R$ 117,00"},
    {"produto": "LENÇOL SOLTEIRO MALHA", "preco": "R$ 90,00"},
    {"produto": "LENÇOL QUEEN MALHA", "preco": "R$ 140,00"},
    {"produto": "LENÇOL KING MALHA", "preco": "R$ 167,00"},
    {"produto": "LENÇOL SUPER KING MALHA", "preco": "R$ 197,00"},
    {"produto": "LENÇOL VIROL CASAL 4 PÇS", "preco": "R$ 180,00"},
    {"produto": "LENÇOL VIROL KING 4 PÇS", "preco": "R$ 230,00"},
    {"produto": "COLCHA MALHA CASAL", "preco": "R$ 178,00"},
    {"produto": "COLCHA LENÇOL CASAL", "preco": "R$ 205,00"},
    {"produto": "COLCHA LENÇOL SOLTEIRO", "preco": "R$ 160,00"},
    {"produto": "COLCHA LENÇOL KING", "preco": "R$ 285,00"},
    {"produto": "COLCHA LENÇOL SUPER KING", "preco": "R$ 297,00"},
    {"produto": "COLCHA RETALHO CASAL", "preco": "R$ 155,00"},
    {"produto": "COLCHA FUXICO CASAL COM BABADO", "preco": "R$ 189,00"},
    {"produto": "COLCHA FUXICO SOLTEIRO SEM BABADO", "preco": "R$ 118,00"},
    {"produto": "COLCHA FUXICO XADREZ CASAL", "preco": "R$ 220,00"},
    {"produto": "COLCHA FUXICO XADREZ SOLTEIRO", "preco": "R$ 139,00"},
    {"produto": "COLCHA BORDADA CASAL SEM BABADO", "preco": "R$ 172,00"},
    {"produto": "COLCHA BORDADA SOLTEIRO SEM BABADO", "preco": "R$ 98,00"},
    {"produto": "COLCHA APLICADA CASAL COM BABADO", "preco": "R$ 189,00"},
    {"produto": "COLCHA DUPLA FACE CASAL LEPPER", "preco": "R$ 189,00"},
    {"produto": "COLCHA DUPLA FACE SOLTEIRO LEPPER", "preco": "R$ 110,00"},
    {"produto": "COLCHA DUPLA FACE QUEEN LEPPER", "preco": "R$ 210,00"},
    {"produto": "COLCHA DUPLA FACE KING LEPPER", "preco": "R$ 220,00"},
    {"produto": "COLCHA DUPLA FACE SUPER KING LEPPER", "preco": "R$ 310,00"},
    {"produto": "COLCHA DUPLA FACE CASAL KSATEX", "preco": "R$ 210,00"},
    {"produto": "COLCHA DUPLA FACE QUEEN KSATEX", "preco": "R$ 230,00"},
    {"produto": "COLCHA DUPLA FACE SOLTEIRO KSATEX", "preco": "R$ 140,00"},
    {"produto": "COLCHA DUPLA FACE ELEGANCE CASAL", "preco": "R$ 256,00"},
    {"produto": "COLCHA DUPLA FACE ELEGANCE SOLTEIRO", "preco": "R$ 192,00"},
    {"produto": "COLCHA DUPLA FACE ELEGANCE QUEEN", "preco": "R$ 265,00"},
    {"produto": "COLCHA DUPLA FACE ELEGANCE KING", "preco": "R$ 279,00"},
    {"produto": "COLCHA DUPLA FACE ELEGANCE SUPER KING", "preco": "R$ 310,00"},
    {"produto": "COLCHA DUPLA FACE MARGARIDA CASAL", "preco": "R$ 256,00"},
    {"produto": "COLCHA DUPLA FACE MARGARIDA SOLTEIRO", "preco": "R$ 192,00"},
    {"produto": "COLCHA DUPLA FACE MARGARIDA SUPER KING", "preco": "R$ 310,00"},
    {"produto": "COLCHA DUPLA FACE MILÃO KING", "preco": "R$ 215,00"},
    {"produto": "COLCHA DUPLA FACE MILÃO SUPER KING", "preco": "R$ 230,00"},
    {"produto": "COLCHA DUPLA FACE BARCELONA CASAL", "preco": "R$ 279,00"},
    {"produto": "COLCHA DUPLA FACE BARCELONA SOLTEIRO", "preco": "R$ 180,00"},
    {"produto": "COLCHA DUPLA FACE SOLTEIRO SULTAN", "preco": "R$ 189,00"},
    {"produto": "COLCHA DUPLA FACE INFANTIL SULTAN", "preco": "R$ 192,00"},
    {"produto": "COLCHA DUPLA FACE INFANTIL LEPPER", "preco": "R$ 168,00"},
    {"produto": "COLCHA DUPLA FACE INFANTIL HABITAT/KSATEX", "preco": "R$ 176,00"},
    {"produto": "COLCHA INFANTIL SEM BABADO", "preco": "R$ 89,00"},
    {"produto": "COLCHA POP CASAL DUPLA FACE 2.15X1.80", "preco": "R$ 108,00"},
    {"produto": "COLCHA HOME DECOR LISA CASAL COSTURADA", "preco": "R$ 298,00"},
    {"produto": "COLCHA PARIS CASAL 3 PÇS", "preco": "R$ 209,00"},
    {"produto": "COLCHA KAROL CASAL 3 PÇS", "preco": "R$ 187,00"},
    {"produto": "COLCHA VENEZA CASAL 3 PÇS", "preco": "R$ 128,00"},
    {"produto": "COLCHA DALLAS QUEEN 3 PÇS", "preco": "R$ 119,00"},
    {"produto": "COLCHA IRIS QUEEN 3 PÇS", "preco": "R$ 206,00"},
    {"produto": "COLCHA REQUINTE CASAL 3 PÇS", "preco": "R$ 158,00"},
    {"produto": "COLCHA REQUINTE SOLTEIRO 2 PÇS", "preco": "R$ 120,00"},
    {"produto": "COLCHA FLORENÇA CASAL 3 PÇS", "preco": "R$ 192,00"},
    {"produto": "COLCHA FLORENÇA QUEEN 3 PÇS", "preco": "R$ 202,00"},
    {"produto": "COLCHA DENVER CASAL 3 PÇS", "preco": "R$ 158,00"},
    {"produto": "COLCHA DENVER KING 3 PÇS", "preco": "R$ 172,00"},
    {"produto": "COLCHA LISBOA KING 3 PÇS", "preco": "R$ 205,00"},
    {"produto": "COBRE LEITO VIENA QUEEN 3 PÇS", "preco": "R$ 230,00"},
    {"produto": "COBRE LEITO ROMÂNTICA QUEEN", "preco": "R$ 305,00"},
    {"produto": "COBERTOR FLANNEL RELEVO 1.80X2.20", "preco": "R$ 138,00"},
    {"produto": "COBERTOR MICROFIBRA CASAL", "preco": "R$ 82,00"},
    {"produto": "COBERTOR ESSENCE CASAL 1.80X2.20", "preco": "R$ 126,00"},
    {"produto": "COBERTOR ESSENCE SOLTEIRO 1.50X2.20", "preco": "R$ 95,00"},
    {"produto": "COBERTOR ESSENCE KING 2.20X2.40", "preco": "R$ 148,00"},
    {"produto": "COBERTOR TOQUE DE SEDA CASAL 1.80X2.20", "preco": "R$ 169,00"},
    {"produto": "COBERTOR TOQUE DE SEDA SOLTEIRO 1.50X2.20", "preco": "R$ 120,00"},
    {"produto": "COBERTOR TOQUE DE SEDA KING 2.20X2.40", "preco": "R$ 205,00"},
    {"produto": "COBERTOR TOQUE DE SEDA SUPER KING 2.40X2.60", "preco": "R$ 247,00"},
    {"produto": "COBERTOR TOQUE DE SEDA INFANTIL 0.90X1.10", "preco": "R$ 75,00"},
    {"produto": "COBERTOR BOREAL CASAL 1.80X2.20", "preco": "R$ 175,00"},
    {"produto": "COBERTOR DIAMOND CASAL 1.180X2.20", "preco": "R$ 175,00"},
    {"produto": "COBERDROM QUEEN LEPPER 2.20X2.40", "preco": "R$ 389,00"},
    {"produto": "EDREDOM HARMONIA SOLTEIRO LEPPER 1.40X2.10", "preco": "R$ 132,00"},
    {"produto": "EDREDOM HARMONIA QUEEN LEPPER 2.10X2.20", "preco": "R$ 189,00"},
    {"produto": "EDREDOM COLOR ART QUEEN CORTTEX 2.10X2.30", "preco": "R$ 158,00"},
    {"produto": "EDREDOM DIVERTIR KIDS LEPPER 1.40X2.10", "preco": "R$ 155,00"},
    {"produto": "MANTA BALLON CASAL 2.00X2.40", "preco": "R$ 206,00"},
    {"produto": "MANTA FOLHAS CASAL 2.00X2.20", "preco": "R$ 215,00"},
    {"produto": "MANTA FOLHAS QUEEN 2.20X2.40", "preco": "R$ 225,00"},
    {"produto": "MANTA FOLHAS KING 2.40X2.60", "preco": "R$ 245,00"},
    {"produto": "MANTA LAÇOS CASAL 2.00X2.20", "preco": "R$ 215,00"},
    {"produto": "MANTA LAÇOS QUEEN 2.20X2.40", "preco": "R$ 225,00"},
    {"produto": "MANTA LAÇOS KING 2.40X2.60", "preco": "R$ 245,00"},
    {"produto": "MANTA MARGARIDA CASAL 2.00X2.20", "preco": "R$ 215,00"},
    {"produto": "MANTA MARGARIDA KING 2.40X2.60", "preco": "R$ 225,00"},
    {"produto": "MANTA PRIMAVERA CASAL 2.00X2.20", "preco": "R$ 215,00"},
    {"produto": "MANTA PRIMAVERA KING 2.40X2.60", "preco": "R$ 225,00"},
    {"produto": "MANTA POÁ CASAL 2.00X2.20", "preco": "R$ 169,00"},
    {"produto": "MANTA POÁ QUEEN 2.20X2.40", "preco": "R$ 179,00"},
    {"produto": "MANTA POÁ KING 2.40X2.60", "preco": "R$ 189,00"},
    {"produto": "MANTA FLANEL CASAL 2.00X2.20", "preco": "R$ 135,00"},
    {"produto": "MANTA FLANEL QUEEN 2.20X2.40", "preco": "R$ 159,00"},
    {"produto": "MANTA WAFER CASAL 2.00X2.40", "preco": "R$ 180,00"},
    {"produto": "MANTA MICROFIBRA CASAL JACQUARD", "preco": "R$ 180,00"},
    {"produto": "MANTA MICROFIBRA UNIQUE", "preco": "R$ 180,00"},
    {"produto": "MANTA INFANTIL LEPPER", "preco": "R$ 115,00"},
    {"produto": "MANTA BABY PELUCIA DIVERSOS", "preco": "R$ 152,00"},
    {"produto": "JOGO DE QUARTO ADULTO", "preco": "R$ 194,00"},
    {"produto": "JOGO DE QUARTO INFANTIL", "preco": "R$ 195,00"},
    {"produto": "JOGO DE CAMA CASAL LEPPER 4 PÇS", "preco": "R$ 162,00"},
    {"produto": "JOGO DE CAMA QUEEN LEPPER 4 PÇS", "preco": "R$ 185,00"},
    {"produto": "JOGO DE CAMA KING LEPPER 4 PÇS", "preco": "R$ 218,00"},
    {"produto": "JOGO DE CAMA DIVERTIR KIDS LEPPER 2 PÇS", "preco": "R$ 88,00"},
    {"produto": "KIT ROMA CASAL 3 PÇS", "preco": "R$ 205,00"},
    {"produto": "KIT FLORATA CASAL 4 PÇS", "preco": "R$ 235,00"},
    {"produto": "KIT GARDEN CASAL 4 PÇS", "preco": "R$ 230,00"},
    {"produto": "KIT GARDEN QUEEN 4 PÇS", "preco": "R$ 240,00"},
    {"produto": "KIT REQUINTE CASAL 4 PÇS", "preco": "R$ 251,00"},
    {"produto": "KIT REQUINTE QUEEN 4 PÇS", "preco": "R$ 258,00"},
    {"produto": "KIT VENEZA CASAL 4 PÇS", "preco": "R$ 245,00"},
    {"produto": "KIT OURO QUEEM 4 PÇS", "preco": "R$ 305,00"},
    {"produto": "CORTINA PREMIUM", "preco": "R$ 225,00"},
    {"produto": "CORTINA ELEGANCE", "preco": "R$ 225,00"},
    {"produto": "CORTINA JACGUARD", "preco": "R$ 235,00"},
    {"produto": "CORTINA VIENA", "preco": "R$ 159,00"},
    {"produto": "CORTINA BARCELONA 1.80x2.20", "preco": "R$ 165,00"},
    {"produto": "CORTINA BARCELONA 2.60X3.00", "preco": "R$ 207,00"},
    {"produto": "CORTINA BLACKOUT COM TECIDO 2.80X2.80", "preco": "R$ 215,00"},
    {"produto": "CORTINA BLACKOUT COM TECIDO 2.80X1.80", "preco": "R$ 168,00"},
    {"produto": "CORTINA PRATIKA LISA 2.60X2.30", "preco": "R$ 198,00"},
    {"produto": "CORTINA PRATIKA LISA SLIM 2.60X2.30", "preco": "R$ 198,00"},
    {"produto": "CORTINA PRATIKA AMASSADA SLIM 2.60X2.30", "preco": "R$ 215,00"},
    {"produto": "CORTINA PRATIKA LISA SLIM 2.60X1.70", "preco": "R$ 192,00"},
    {"produto": "CORTINA PRATIKA AMASSADA SLIM 2.60X1.70", "preco": "R$ 192,00"},
    {"produto": "CORTINA PRATIKA LISA SLIM 2.40X1.60", "preco": "R$ 155,00"},
    {"produto": "CORTINA PRATIKA LISA SLIM 3.60X2.50", "preco": "R$ 279,00"},
    {"produto": "CORTINA PRATIKA AMASSADA SLIM 3.60X2.50", "preco": "R$ 279,00"},
    {"produto": "CORTINA DE COZINHA BORDADA", "preco": "R$ 148,00"},
    {"produto": "VARÃO KIT PRATIKO PRO 19MMX2.00M", "preco": "R$ 42,00"},
    {"produto": "VARÃO KIT PRATIKO PRO 19MMX1.50M", "preco": "R$ 32,00"},
    {"produto": "TOALHA DE MESA POP 4 LUGARES", "preco": "R$ 39,00"},
    {"produto": "TOALHA DE MESA POP 6 LUGARES", "preco": "R$ 56,00"},
    {"produto": "TOALHA DE MESA SUPER PRÁTICA 6 LUGARES", "preco": "R$ 80,00"},
    {"produto": "TOALHA DE MESA TÉRMICA 4 CAD.", "preco": "R$ 45,00"},
    {"produto": "TOALHA DE MESA ANDRESSA 1.45X2.15", "preco": "R$ 58,00"},
    {"produto": "TOALHA DE COZINHA", "preco": "R$ 24,00"},
    {"produto": "TRAVESSEIRO COMFORT", "preco": "R$ 60,00"},
    {"produto": "TRAVESSEIRO SONHARE SULTAN", "preco": "R$ 69,00"},
    {"produto": "TRAVESSEIRO SILICONE HEDRONS", "preco": "R$ 61,00"},
    {"produto": "TRAVESSEIRO CACHORRINHO", "preco": "R$ 68,00"},
    {"produto": "TOALHA DE BANHO ELEGANCE", "preco": "R$ 62,00"},
    {"produto": "TOALHA DE BANHO DECORADA", "preco": "R$ 50,00"},
    {"produto": "TOALHA DE BANHO BORDADA", "preco": "R$ 59,00"},
    {"produto": "TOALHA DE BANHO SOFISTICATTA", "preco": "R$ 58,00"},
    {"produto": "TOALHA DE BANHO AMSTERDAM", "preco": "R$ 56,00"},
    {"produto": "TOALHA DE BANHO ARABESCO JACKGURAD", "preco": "R$ 54,00"},
    {"produto": "TOALHA DE BANHO SAMIRA", "preco": "R$ 50,00"},
    {"produto": "TOALHA DE BANHO LEPPER UNID.", "preco": "R$ 58,00"},
    {"produto": "TOALHA DE BANHO LEPPER KING UNID.", "preco": "R$ 60,00"},
    {"produto": "JOGO DE BANHO LEPPER ELE E ELA LEPPER", "preco": "R$ 120,00"},
    {"produto": "TOALHA DE BANHO INFANTIL LEPPER", "preco": "R$ 58,00"},
    {"produto": "TOALHA DE BANHO INFANTIL COM CAPUZ LEPPER", "preco": "R$ 92,00"},
    {"produto": "TOALHA DE ROSTO LEPPER", "preco": "R$ 28,00"},
    {"produto": "TOALHA DE ROSTO", "preco": "R$ 25,00"},
    {"produto": "PANO DE PRATO", "preco": "R$ 7,00"},
    {"produto": "PANO DE PRATO FELPUDO", "preco": "R$ 14,00"},
    {"produto": "PANO DE COPA FELPUDO", "preco": "R$ 12,00"},
    {"produto": "SEMANINHA ATOALHADA", "preco": "R$ 98,00"},
    {"produto": "JOGO SEMANINHA BORDADO", "preco": "R$ 85,00"},
    {"produto": "ALMOFADA INFANTIL LEPPER", "preco": "R$ 48,00"},
    {"produto": "ALMOFADA EMOJIS", "preco": "R$ 38,00"},
    {"produto": "ALMOFADA NÓ", "preco": "R$ 48,00"},
    {"produto": "KIT ALMOFADA FLOR", "preco": "R$ 78,00"},
    {"produto": "JOGO DE ALMOFADA 5 PÇS", "preco": "R$ 170,00"},
    {"produto": "JOGO DE ALMOFADA INFANTIL 4 PÇS", "preco": "R$ 115,00"},
    {"produto": "KIT DE COZINHA PATCH 3 PÇS", "preco": "R$ 105,00"},
    {"produto": "JOGO DE COZINHA BALI 6 CAD.", "preco": "R$ 210,00"},
    {"produto": "JOGO DE COZINHA BALI 4 CAD.", "preco": "R$ 188,00"},
    {"produto": "JOGO DE COZINHA ESTAMPADO 16 PÇS", "preco": "R$ 198,00"},
    {"produto": "JOGO DE COZINHA BORDADO 15 PÇS", "preco": "R$ 192,00"},
    {"produto": "JOGO DE COZINHA BORDADO 12 PÇS", "preco": "R$ 132,00"},
    {"produto": "JOGO DE COZINHA ROMA BORDADO 10 PÇS", "preco": "R$ 198,00"},
    {"produto": "JOGO DE COZINHA ROMA BORDADO 11 PÇS", "preco": "R$ 215,00"},
    {"produto": "JOGO DE COZINHA ROMA BORDADO 12 PÇS", "preco": "R$ 220,00"},
    {"produto": "JOGO DE COZINHA INCRÍVEL BORDADO 13 PÇS", "preco": "R$ 260,00"},
    {"produto": "JOGO DE COZINHA INCRÍVEL ESTAMPADO 13 PÇS", "preco": "R$ 205,00"},
    {"produto": "JOGO DE COZINHA INCRÍVEL ESTAMPADO 11 PÇS", "preco": "R$ 170,00"},
    {"produto": "JOGO DE BANHEIRO ALABAMA 2 PÇS", "preco": "R$ 68,00"},
    {"produto": "JOGO DE BANHEIRO BIDAR 3 PÇS", "preco": "R$ 78,00"},
    {"produto": "JOGO DE BANHEIRO CONGO 3 PÇS", "preco": "R$ 92,00"},
    {"produto": "JOGO DE BANHEIRO PILÃO 3 PÇS", "preco": "R$ 85,00"},
    {"produto": "JOGO DE BANHEIRO GATO 3 PÇS", "preco": "R$ 89,00"},
    {"produto": "JOGO DE BANHEIRO ONIX 3 PÇS", "preco": "R$ 89,00"},
    {"produto": "KIT DE BANHEIRO CLASSIC 3 PÇS", "preco": "R$ 95,00"},
    {"produto": "TAPETE PASSADEIRA CLASSIC 50X1.80", "preco": "R$ 115,00"},
    {"produto": "TAPETE PASSADEIRA MOSCOU 60X2.00", "preco": "R$ 115,00"},
    {"produto": "JOGO DE TAPETE PASSADEIRA ONIX 3 PÇS", "preco": "R$ 129,00"},
    {"produto": "JOGO DE TAPETE PASSADEIRA PILÃO 3 PÇS", "preco": "R$ 145,00"},
    {"produto": "JOGO DE TAPETE PASSADEIRA GATO 3 PÇS", "preco": "R$ 122,00"},
    {"produto": "KIT DE QUARTO POLO SUL CLASSIC 3 PÇS", "preco": "R$ 175,00"},
    {"produto": "TAPETE DE BANHEIRO UTAH", "preco": "R$ 26,00"},
    {"produto": "TAPETE DE BANHEIRO ALABAMA", "preco": "R$ 32,00"},
    {"produto": "TAPETE DE BANHEIRO MISSISIPI", "preco": "R$ 58,00"},
    {"produto": "TAPETE DE BANHEIRO MONTERREY", "preco": "R$ 32,00"},
    {"produto": "TAPETE DE BANHEIRO SERGIPE", "preco": "R$ 39,00"},
    {"produto": "TAPETE DALLAS", "preco": "R$ 42,00"},
    {"produto": "TAPETE NICE", "preco": "R$ 38,00"},
    {"produto": "TAPETE APOLO", "preco": "R$ 36,00"},
    {"produto": "TAPETE BEM-VINDO", "preco": "R$ 30,00"},
    {"produto": "TAPETE MICROSOFT", "preco": "R$ 34,00"},
    {"produto": "TAPETE DEDINHO P", "preco": "R$ 38,00"},
    {"produto": "TAPETE DEDINHO G", "preco": "R$ 52,00"},
    {"produto": "TAPETE BIDAR", "preco": "R$ 24,00"},
    {"produto": "TAPETE BIDAR COLORIDO", "preco": "R$ 28,00"},
    {"produto": "TAPETE KILIM", "preco": "R$ 22,00"},
    {"produto": "TAPETE INFANTIL", "preco": "R$ 172,00"},
    {"produto": "TAPETE CLASSIC 45X70", "preco": "R$ 34,00"},
    {"produto": "TAPETE CLASSIC 40X60", "preco": "R$ 32,00"},
    {"produto": "TAPETE CLASSIC EVA 40X60", "preco": "R$ 30,00"},
    {"produto": "TAPETE DE SALA 2.00X2.50", "preco": "R$ 400,00"},
    {"produto": "TAPETE DE SALA 1.00X2.50", "preco": "R$ 300,00"},
    {"produto": "TAPETE DE SALA 1.00X1.50", "preco": "R$ 230,00"},
    {"produto": "TAPETE DE SALA MOSCOU 2.00X2.40", "preco": "R$ 320,00"},
    {"produto": "TAPETE DE SALA MOSCOU 1.40X2.00", "preco": "R$ 210,00"},
    {"produto": "TAPETE DE SALA KSATEX 1.40X2.00", "preco": "R$ 280,00"},
    {"produto": "TAPETE VELUDO KSATEX 1.00X1.40", "preco": "R$ 220,00"},
    {"produto": "TAPETE VELUDO KSATEX 50X1.00", "preco": "R$ 62,00"},
    {"produto": "TAPETE FLANELADO 1.40X2.00", "preco": "R$ 298,00"},
    {"produto": "TAPETE DONATELLO 1.40X2.00", "preco": "R$ 298,00"},
    {"produto": "TAPETE DE SALA ESMERALDA 1.50X2.00", "preco": "R$ 152,00"},
    {"produto": "TAPETE DE SALA JADE 1.50x2.00", "preco": "R$ 259,00"},
    {"produto": "TAPETE DE SALA DETROIT 1.50X2.00", "preco": "R$ 315,00"},
    {"produto": "TAPETE DE SALA CLASSIC 1.50X2.00", "preco": "R$ 305,00"},
    {"produto": "TAPETE DE SALA CLASSIC 1.00X1.50", "preco": "R$ 198,00"},
    {"produto": "TAPETE DE SALA JAZZ 1.50X2.00", "preco": "R$ 315,00"},
    {"produto": "TAPETE JAZZ KIDS 1.00X1.50", "preco": "R$ 192,00"},
    {"produto": "TAPETE REDONDO CIRCLE 75 CM", "preco": "R$ 75,00"},
    {"produto": "TAPETE DE SALA REDONDO CLASSIC", "preco": "R$ 110,00"},
    {"produto": "TAPETE GATO 2 PÇS", "preco": "R$ 45,00"},
    {"produto": "TAPETE PILÃO 2 PÇS", "preco": "R$ 79,00"},
    {"produto": "TAPETE VELUDO P", "preco": "R$ 34,00"},
    {"produto": "TAPETE VELUDO G", "preco": "R$ 48,00"},
    {"produto": "TAPETE VELUDO GG", "preco": "R$ 55,00"},
    {"produto": "TAPETE DE RETALHO P", "preco": "R$ 14,00"},
    {"produto": "TAPETE DE RETALHO G", "preco": "R$ 120,00"},
    {"produto": "TAPETE FLU FLU MALHA", "preco": "R$ 42,00"},
    {"produto": "BONECAS", "preco": "R$ 58,00"},
    {"produto": "LUCAS NETO", "preco": "R$ 78,00"},
    {"produto": "MINIONS", "preco": "R$ 58,00"},
    {"produto": "REDE INFANTIL", "preco": "R$ 105,00"},
    {"produto": "REDE G", "preco": "R$ 210,00"},
    {"produto": "CAMISA DE PROTEÇÃO", "preco": "R$ 76,00"},
    {"produto": "BERMUDA TACTEL", "preco": "R$ 42,00"},
    {"produto": "CUECA BOX ADULTO", "preco": "R$ 24,00"},
    {"produto": "CUECA BOX INFANTIL", "preco": "R$ 18,00"},
    {"produto": "CALCINHA ADULTO", "preco": "R$ 18,00"},
    {"produto": "CONJUNTO LIGERIE", "preco": "R$ 89,00"},
    {"produto": "CAIXA DE SOM BOLINHA", "preco": "R$ 158,00"},
    {"produto": "TRITURADOR 3 LAMINAS", "preco": "R$ 62,00"},
    {"produto": "KIT SECA SALADAS + TRITURADOR", "preco": "R$ 139,00"},
    {"produto": "KIT UTENSILIOS SLIM 3 PÇS", "preco": "R$ 22,00"},
    {"produto": "KIT ORGANIZADOR QUADRADO 5 PÇS", "preco": "R$ 78,00"},
    {"produto": "KIT MULTIUSO 5 PÇS SULTAN", "preco": "R$ 142,00"},
    {"produto": "KIT MULTIUSO 4 PÇS SULTAN", "preco": "R$ 110,00"},
    {"produto": "KIT DE BACIA 4 PÇS", "preco": "R$ 155,00"},
    {"produto": "KIT NOIVA 5 PÇS VIEIRA", "preco": "R$ 385,00"},
    {"produto": "PANELA DE PRESSÃO 7,0 L ALIANÇA", "preco": "R$ 275,00"},
    {"produto": "PANELA DE PRESSÃO 5,0 L ALIANÇA FECHO EXTERNO", "preco": "R$ 302,00"},
    {"produto": "PANELA DE PRESSÃO 4,5 L ALIANÇA", "preco": "R$ 242,00"},
    {"produto": "PANELA DE PRESSÃO 4,5 L DONA ADA", "preco": "R$ 175,00"},
    {"produto": "PANELA DE PRESSÃO 2,5 L ALIANÇA", "preco": "R$ 192,00"},
    {"produto": "PANELA DE PRESSÃO 2,5L VIEIRA", "preco": "R$ 145,00"},
    {"produto": "PANELA DE PRESSÃO 7,0L VIEIRA", "preco": "R$ 215,00"},
    {"produto": "PANELA DE PRESSÃO 4,5L VIEIRA", "preco": "R$ 169,00"},
    {"produto": "FRIGIDEIRA ALIANÇA", "preco": "R$ 65,00"},
    {"produto": "FRIGIDEIRA COM TAMPA ALIANÇA", "preco": "R$ 130,00"},
    {"produto": "FRIGIDEIRA FUNDA COM TAMPA ALIANÇA", "preco": "R$ 146,00"},
    {"produto": "FRIGIDEIRA FUNDA QUADRADA COM TAMPA ALIANÇA", "preco": "R$ 165,00"},
    {"produto": "FRIGIDEIRA QUADRADA WOK 2 ALÇAS ALIANÇA", "preco": "R$ 271,00"},
    {"produto": "CONJUNTO ASSADEIRA DONA ADA 4PÇS", "preco": "R$ 137,00"},
    {"produto": "COPO TÉRMICO STANLEY 473 ML", "preco": "R$ 125,00"},
    {"produto": "GARRAFA TÉRMICA ESPORTIVA STANLEY", "preco": "R$ 108,00"},
    {"produto": "KIT DE GARRAFA TÉRMICA COM XÍCARA STANLEY", "preco": "R$ 142,00"},
    {"produto": "KIT DE GARRAFA 4 EM 1", "preco": "R$ 162,00"},
    {"produto": "KIT DE GARRAFA 3 EM 1", "preco": "R$ 115,00"},
    {"produto": "CANECA INOX 450 ML", "preco": "R$ 15,00"},
    {"produto": "GARRAFA PLÁSTICA KIDS 220 ML", "preco": "R$ 14,50"},
    {"produto": "CANECO QUADRADO ALIANÇA 2,1 L", "preco": "R$ 98,00"},
    {"produto": "CANECO DONA ADA 2,700 L", "preco": "R$ 45,00"},
    {"produto": "CAFETEIRA POLIDA 1L VIEIRA", "preco": "R$ 98,00"},
    {"produto": "CUSCUBULE NORDESTINO 1L VIEIRA", "preco": "R$ 98,00"},
    {"produto": "JOGO DE COPOS 3 PÇS 450 ML", "preco": "R$ 42,00"},
    {"produto": "JOGO DE COPOS 3 PÇS 330 ML", "preco": "R$ 28,00"},
    {"produto": "JOGO DE PANELA IMPÉRIO 5 PÇS VIEIRA", "preco": "R$ 305,00"},
    {"produto": "JOGO DE PANELA 5 PÇS ALIANÇA", "preco": "R$ 649,00"},
    {"produto": "JOGO DE PANELA 5 PÇS CAVA", "preco": "R$ 590,00"},
    {"produto": "JOGO DE CANECO 3 PÇS VIEIRA", "preco": "R$ 115,00"},
    {"produto": "JOGO FAQUEIRO PRESTIGE 20 PÇS", "preco": "R$ 105,00"},
    {"produto": "JOGO FAQUEIRO SATURNO 24 PÇS", "preco": "R$ 80,00"},
    {"produto": "JOGO FAQUEIRO INOX VENUS 24 PÇS", "preco": "R$ 128,00"},
    {"produto": "JOGO FAQUEIRO PRIMAVERA 24 PÇS", "preco": "R$ 72,00"},
    {"produto": "JOGO TALHER RECIFE 24 PÇS", "preco": "R$ 75,00"},
    {"produto": "JOGO DE COLHER RECIFE 4 PÇS", "preco": "R$ 15,00"},
    {"produto": "JOGO DE GARFO RECIFE 4 PÇS", "preco": "R$ 15,00"},
    {"produto": "JOGO DE FACA RECIFE 4 PÇS", "preco": "R$ 15,00"},
    {"produto": "FACA ATTUALE 8\" 33 CM", "preco": "R$ 32,00"},
    {"produto": "FACA ATTUALE 5\" 23,5 CM", "preco": "R$ 21,00"},
    {"produto": "FACA PRECISION 8\" 32,8 CM", "preco": "R$ 46,00"},
    {"produto": "FACA PRECISION 8\" 32,4 CM", "preco": "R$ 39,00"},
    {"produto": "DOCE DE LEITE KREMOLAT", "preco": "R$ 45,00"}
  ];
  
  function mostrarSugestoes() {
    const input = document.getElementById('nomeProduto');
    const valorInput = input.value.toUpperCase();
    
    const sugestoes = produtos
    
      .filter(item => item.produto.toUpperCase().includes(valorInput))
      .map(item => item.produto);
      

    const sugestoesDiv = document.getElementById('sugestoes');
    sugestoesDiv.innerHTML = '';
  
    sugestoes.forEach((sugestao, index) => {
        const sugestaoElement = document.createElement('div');
        sugestaoElement.textContent = sugestao;
        sugestaoElement.classList.add('sugestao-item');
        sugestaoElement.addEventListener('click', () => {
          input.value = sugestao;
          exibirInformacoesProduto();
          limparSugestoes();
          input.value = '';  // Limpa o input após selecionar a sugestão
        });
        sugestoesDiv.appendChild(sugestaoElement);
      });
  }
  
  function limparSugestoes() {
    document.getElementById('sugestoes').innerHTML = '';
    
  }
  
  function exibirInformacoesProduto() {
    
    const nomeProduto = document.getElementById('nomeProduto').value.toUpperCase();

    const produto = produtos.find(item => item.produto.toUpperCase() === nomeProduto);
  
    if (produto) {
        const infoProduto = `<span class="produtoValor">Produto: ${produto.produto}</span><span class="preco">Preço: ${produto.preco}</span>`;
        document.getElementById('infoProduto').innerHTML = infoProduto;
    } else {
      document.getElementById('infoProduto').textContent = 'Produto não encontrado';
    }
    
  }
  